// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
public class ContactTest {
  private WebDriver driver;

  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void contact() {
    driver.get("http://localhost/addressbook/");
    driver.manage().window().setSize(new Dimension(933, 686));
    driver.findElement(By.name("pass")).sendKeys("secret");
    driver.findElement(By.name("user")).sendKeys("admin");
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
    driver.findElement(By.linkText("add new")).click();
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys("Name");
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("middlename")).click();
    driver.findElement(By.name("middlename")).sendKeys("MiddleN");
    driver.findElement(By.name("lastname")).click();
    driver.findElement(By.name("lastname")).sendKeys("LastN");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("Nickname");
    driver.findElement(By.name("title")).click();
    driver.findElement(By.name("title")).sendKeys("Title");
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("company")).click();
    driver.findElement(By.name("company")).sendKeys("Company");
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).sendKeys("Addresss");
    driver.findElement(By.name("home")).click();
    driver.findElement(By.name("home")).sendKeys("home");
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("mobile")).click();
    driver.findElement(By.name("mobile")).sendKeys("Mobile");
    driver.findElement(By.name("work")).click();
    driver.findElement(By.name("work")).sendKeys("Work");
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("fax")).click();
    driver.findElement(By.name("fax")).sendKeys("Fax");
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("1@e1.ru");
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("email2")).click();
    driver.findElement(By.name("email2")).sendKeys("2@e1.ru");
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("email3")).click();
    driver.findElement(By.name("email3")).sendKeys("3@e1.ru");
    driver.findElement(By.name("theform")).click();
    driver.findElement(By.name("homepage")).click();
    driver.findElement(By.name("homepage")).sendKeys("homepage");
    driver.findElement(By.name("theform")).click();
    {
      WebElement dropdown = driver.findElement(By.name("bday"));
      dropdown.findElement(By.xpath("//option[. = '28']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(61) > option:nth-child(30)")).click();
    {
      WebElement dropdown = driver.findElement(By.name("bmonth"));
      dropdown.findElement(By.xpath("//option[. = 'December']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(62) > option:nth-child(13)")).click();
    driver.findElement(By.name("byear")).click();
    driver.findElement(By.name("byear")).sendKeys("2020");
    {
      WebElement dropdown = driver.findElement(By.name("aday"));
      dropdown.findElement(By.xpath("//option[. = '31']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(66) > option:nth-child(33)")).click();
    driver.findElement(By.name("amonth")).click();
    {
      WebElement dropdown = driver.findElement(By.name("amonth"));
      dropdown.findElement(By.xpath("//option[. = 'January']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(67) > option:nth-child(2)")).click();
    driver.findElement(By.name("ayear")).click();
    driver.findElement(By.name("ayear")).sendKeys("2030");
    driver.findElement(By.name("new_group")).click();
    {
      WebElement dropdown = driver.findElement(By.name("new_group"));
      dropdown.findElement(By.xpath("//option[. = 'name']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(71) > option:nth-child(8)")).click();
    driver.findElement(By.cssSelector("input:nth-child(75)")).click();
    driver.findElement(By.linkText("home page")).click();
  }
}
