/* Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("http://localhost/addressbook/");
    driver.manage().window().setSize(new Dimension(934, 672));
    driver.findElement(By.linkText("groups")).click();
    driver.findElement(By.cssSelector(".group:nth-child(9) > input")).click();
    driver.findElement(By.cssSelector(".group:nth-child(8) > input")).click();
    driver.findElement(By.cssSelector(".group:nth-child(10) > input")).click();
    driver.findElement(By.cssSelector(".group:nth-child(11) > input")).click();
    driver.findElement(By.cssSelector(".group:nth-child(12) > input")).click();
    driver.findElement(By.cssSelector("form:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".group:nth-child(13) > input")).click();
    driver.findElement(By.cssSelector(".group:nth-child(14) > input")).click();
    driver.findElement(By.cssSelector(".group:nth-child(15) > input")).click();
    driver.findElement(By.cssSelector(".group:nth-child(16) > input")).click();
    driver.findElement(By.cssSelector(".group:nth-child(17) > input")).click();
  }
}*/
